# Generated by Django 5.0.1 on 2024-01-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='y', max_length=50),
            preserve_default=False,
        ),
    ]
